server:
  port: 8001
   
mybatis:
  #实体类所做包
  type-aliases-package: com.dreamworks.sms.teacher.dto
  #mapper.xml所在位置
  mapper-locations: classpath:sqlmap/sms/*.xml 
  
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
spring:
    #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: a123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    

